name: Clippy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: taiki-e/install-action@cargo-hack
    - name: Clippy deny warnings
      run: cargo hack clippy --feature-powerset --exclude-features ipc --all-targets -- -D warnings
